---
- set_fact:
    pkg_name: "{{ 'systemd' if (ansible_distribution == 'Debian' and ansible_distribution_major_version is version('10', '<=')) else 'systemd-timesyncd' }}"

- name: Install systemd-timesyncd
  package:
    name: "{{ pkg_name }}"

- name: Set timezone
  timezone:
    name: "{{ timesync_timezone }}"
  notify: systemd-timesyncd configuration changed

- name: Configure systemd-timesyncd
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: 0644
    owner: root
    group: root
  notify: systemd-timesyncd configuration changed

- name: Start and enable systemd-timesyncd
  service:
    name: systemd-timesyncd.service
    enabled: yes
    state: started
